### ISSUE TITLE
Request for Problem Resolution

### ISSUE THREAD

**Issue by CatPC7345** [NeuroAI-HD/HD-SEQ-ID#1]
I'm having trouble creating a virtual environment using conda. When I execute the following command on Ubuntu 20.04, I receive an error requesting Python 3.8 or higher, and it also states that codecov=2.1.12 cannot be found. I've tried different versions of anaconda3 and miniconda3, but the same error persists. Besides, I encounter errors when trying to upgrade to Python 3.8 with conda. I would appreciate it if you could provide a solution.

`conda env create --name <ENVNAME> --file=hd-seq-id_environment.yml`

**Comment by navalpablo** [comment]
Same here. Would appreciate revision of yml file. Many libraries demand 3.8 or higher, if python version is changed to 3.8 in yml other errors appear.

**Comment by mamahmutoglu** [comment]
Thank your for informing about this issue!
I could replicate the error and now updated the .yml file. I made slight changes in the "hd_seq_id" file and included a feature to export prediction outputs to a CSV file in the output folder. 
Please try to install the new version from start. It works on Ubuntu 18.04 with FSL 5.0.9 and Python version 3.9 without problems.
To avoid similar issues, I'm going to include a docker version soon.

**Comment by adrianvallsc** [comment]
Same here, still with problems with the environment. Is it possible to install it in MacOS?

**Comment by mamahmutoglu** [comment]
We are building a docker image, so that you don't need to deal with the issues of creating the environment from the .yml file. The instructions and the docker image itself will be available by mid January (next week).  
In case you're having issues in MacOS, that my be caused by hardware incompatibilities, we recommend you to try to create the environment in another machine.

**Comment by CatPC7345** [comment]
I was able to implement HD-SEQ-ID using Docker. Thank you very much.
